### ISSUE TITLE
how to set background opacity and letter spacing?

### ISSUE THREAD

**Issue by ArsalanReal** [nikartm/FitButton#2]
how to do following things?

1- Set Opacity
2- Letter Spacing
3- Keep icon most left , margin adding effect to center text as well

**Comment by nikartx** [comment]
Hi ArsalanReal,

1. You can use a hexadecimal color code, small FAQ: https://gist.github.com/nikartm/c02ba9f2dc8dd59ab18a62b8982e17e6
2. Unfortunately, this feature is not currently supported, but I want to add it in the next release.
3. Sorry, I didn't quite understand what you would like to do. Could you try to describe in more detail?
Hope this example helps you:
```
    <com.github.nikartm.button.FitButton
        android:layout_width="250dp"
        android:layout_height="48dp"
        android:layout_margin="16dp"
        android:layout_gravity="center"
        android:gravity="center_vertical"
        app:fb_shape="rectangle"
        app:fb_rippleColor="#42757575"
        app:fb_iconPosition="left"
        app:fb_iconMarginStart="7dp"
        app:fb_icon="@drawable/ic_home"
        app:fb_iconWidth="30dp"
        app:fb_iconHeight="30dp"
        app:fb_textColor="#222222"
        app:fb_textPaddingStart="24dp"
        app:fb_text="Home"
        app:fb_textStyle="bold"
        app:fb_backgroundColor="#EEEEEE"/>
```
